# Generated by Django 4.0.2 on 2022-03-15 08:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shippinginformation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='USA', max_length=2),
        ),
    ]
