# Generated by Django 4.0.2 on 2022-03-15 07:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginformation',
            name='country',
            field=django_countries.fields.CountryField(default='USA', max_length=2),
        ),
    ]
